//@version=6
indicator("GBPUSD SMC PRO V6.0 Professional", overlay=true, max_labels_count=500, max_lines_count=500)

//==================================================
// GBPUSD SMC PRO V6.0
// Professional Smart Money Concept Engine
//==================================================

// Version
version = "V6.0"

// Future modules:
// 1. Core Trend Engine
// 2. Multi Timeframe Bias
// 3. BOS / CHoCH
// 4. Liquidity Sweep
// 5. Fair Value Gap
// 6. Order Block
// 7. Entry Score
// 8. Risk Engine
// 9. Dashboard
// 10. Alerts
//==================================================
// MODULE 1 - CORE TREND ENGINE
//==================================================

// Inputs
emaLength = input.int(200, "EMA Length")


// Current timeframe EMA
ema200 = ta.ema(close, emaLength)

plot(ema200, title="EMA 200", color=color.orange, linewidth=2)


//==================================================
// MULTI TIMEFRAME TREND
//==================================================

getTrend(tf) =>
    c = request.security(syminfo.tickerid, tf, close)
    e = request.security(syminfo.tickerid, tf, ta.ema(close, emaLength))
    c > e ? 1 : -1


h4Trend  = getTrend("240")
h1Trend  = getTrend("60")
m15Trend = getTrend("15")
m5Trend  = getTrend("5")


// Trend Text

trendText(value)=>
    value == 1 ? "BULLISH" : "BEARISH"


//==================================================
// BASIC BIAS
//==================================================

marketBias =
     h4Trend == 1 and h1Trend == 1 ? "BULLISH" :
     h4Trend == -1 and h1Trend == -1 ? "BEARISH" :
     "MIXED"



//==================================================
// MODULE 1 DASHBOARD
//==================================================

var table v6Dash = table.new(position.top_right, 2, 6)


if barstate.islast

    table.cell(v6Dash,0,0,"SMC PRO V6.0")

    table.cell(v6Dash,0,1,"H4")
    table.cell(v6Dash,1,1,trendText(h4Trend))

    table.cell(v6Dash,0,2,"H1")
    table.cell(v6Dash,1,2,trendText(h1Trend))

    table.cell(v6Dash,0,3,"M15")
    table.cell(v6Dash,1,3,trendText(m15Trend))

    table.cell(v6Dash,0,4,"M5")
    table.cell(v6Dash,1,4,trendText(m5Trend))

    table.cell(v6Dash,0,5,"BIAS")
    table.cell(v6Dash,1,5,marketBias)














































































































































































































































































































































